# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'MedicineReminder' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MedicineReminder

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 4.7.0'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  pod 'Firebase/AdMob'
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Performance'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'
  pod 'FirebaseSwizzlingUtilities', '1.0.0'
  pod 'react-native-calendar-events', :path => '../node_modules/react-native-calendar-events'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
      # 'BatchedBridge', # Required For React Native 0.45.0+
      'Core',
      'ART',
      'DevSupport',
      'RCTNetwork',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      # Add any other subspecs you want to use in your project
      ]
end
